import { Schema as S } from "effect";
import { sId } from "./schemas/genericId";

// CONST -----------------------------------------------------------------------------------------------------------------------------------
export const FIELDS = {
  casts: {
    characterId: sId("characters"),
    personId: sId("persons"),
    showId: sId("shows"),
  },
  channels: {
    apiId: S.Int,
    countryId: S.OptionFromNullOr(sId("countries")),
    name: S.String,
    officialSite: S.OptionFromNullOr(S.String),
  },
  characters: {
    apiId: S.Int,
    image: S.NullOr(S.String),
    name: S.String,
    thumbnail: S.NullOr(S.String),
  },
  countries: {
    code: S.String,
    name: S.String,
    timezone: S.String,
  },
  episodes: {
    airdate: S.String,
    airstamp: S.String,
    airtime: S.String,
    apiId: S.Int,
    image: S.NullOr(S.String),
    isWatched: S.Boolean,
    name: S.String,
    number: S.NullOr(S.Int),
    preference: S.Literals(["favorite", "ignored", "unset"]),
    rating: S.NullOr(S.Number),
    runtime: S.NullOr(S.Int),
    season: S.Int,
    showId: sId("shows"),
    summary: S.NullOr(S.String),
    thumbnail: S.NullOr(S.String),
  },
  fetcher: {
    created: S.Int,
    isPending: S.Boolean,
    lastPage: S.Int,
    lastUpdated: S.Int,
  },
  persons: {
    apiId: S.Int,
    birthday: S.NullOr(S.String),
    countryId: S.NullOr(sId("countries")),
    deathday: S.NullOr(S.String),
    gender: S.NullOr(S.String),
    image: S.NullOr(S.String),
    name: S.String,
    thumbnail: S.NullOr(S.String),
    updated: S.NullOr(S.Int),
  },
  shows: {
    apiId: S.Int,
    channelId: S.OptionFromNullOr(sId("channels")),
    ended: S.OptionFromNullOr(S.String),
    genres: S.Array(S.String),
    image: S.OptionFromNullOr(S.String),
    name: S.String,
    officialSite: S.OptionFromNullOr(S.String),
    premiered: S.OptionFromNullOr(S.String),
    preference: S.Literals(["favorite", "ignored", "unset"]),
    rating: S.Number,
    status: S.Literals(["Ended", "In Development", "Running", "To Be Determined"]),
    summary: S.OptionFromNullOr(S.String),
    trackEpisodes: S.Boolean,
    thumbnail: S.OptionFromNullOr(S.String),
    updated: S.Int,
    weight: S.Int,
  },
} as const;
