/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsTrendingRouteImport } from './routes/shows.trending'
import { Route as ShowsTopRatedRouteImport } from './routes/shows.top-rated'
import { Route as ShowsFavoritesRouteImport } from './routes/shows.favorites'
import { Route as ShowsShowIdRouteImport } from './routes/shows.$showId'
import { Route as EpisodesUpcomingRouteImport } from './routes/episodes.upcoming'
import { Route as EpisodesUnwatchedRouteImport } from './routes/episodes.unwatched'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsTrendingRoute = ShowsTrendingRouteImport.update({
  id: '/shows/trending',
  path: '/shows/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsTopRatedRoute = ShowsTopRatedRouteImport.update({
  id: '/shows/top-rated',
  path: '/shows/top-rated',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsFavoritesRoute = ShowsFavoritesRouteImport.update({
  id: '/shows/favorites',
  path: '/shows/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdRoute = ShowsShowIdRouteImport.update({
  id: '/shows/$showId',
  path: '/shows/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesUpcomingRoute = EpisodesUpcomingRouteImport.update({
  id: '/episodes/upcoming',
  path: '/episodes/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesUnwatchedRoute = EpisodesUnwatchedRouteImport.update({
  id: '/episodes/unwatched',
  path: '/episodes/unwatched',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/episodes/unwatched': typeof EpisodesUnwatchedRoute
  '/episodes/upcoming': typeof EpisodesUpcomingRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/shows/favorites': typeof ShowsFavoritesRoute
  '/shows/top-rated': typeof ShowsTopRatedRoute
  '/shows/trending': typeof ShowsTrendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/episodes/unwatched': typeof EpisodesUnwatchedRoute
  '/episodes/upcoming': typeof EpisodesUpcomingRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/shows/favorites': typeof ShowsFavoritesRoute
  '/shows/top-rated': typeof ShowsTopRatedRoute
  '/shows/trending': typeof ShowsTrendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/episodes/unwatched': typeof EpisodesUnwatchedRoute
  '/episodes/upcoming': typeof EpisodesUpcomingRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/shows/favorites': typeof ShowsFavoritesRoute
  '/shows/top-rated': typeof ShowsTopRatedRoute
  '/shows/trending': typeof ShowsTrendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/episodes/unwatched'
    | '/episodes/upcoming'
    | '/shows/$showId'
    | '/shows/favorites'
    | '/shows/top-rated'
    | '/shows/trending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/episodes/unwatched'
    | '/episodes/upcoming'
    | '/shows/$showId'
    | '/shows/favorites'
    | '/shows/top-rated'
    | '/shows/trending'
  id:
    | '__root__'
    | '/'
    | '/episodes/unwatched'
    | '/episodes/upcoming'
    | '/shows/$showId'
    | '/shows/favorites'
    | '/shows/top-rated'
    | '/shows/trending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpisodesUnwatchedRoute: typeof EpisodesUnwatchedRoute
  EpisodesUpcomingRoute: typeof EpisodesUpcomingRoute
  ShowsShowIdRoute: typeof ShowsShowIdRoute
  ShowsFavoritesRoute: typeof ShowsFavoritesRoute
  ShowsTopRatedRoute: typeof ShowsTopRatedRoute
  ShowsTrendingRoute: typeof ShowsTrendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/trending': {
      id: '/shows/trending'
      path: '/shows/trending'
      fullPath: '/shows/trending'
      preLoaderRoute: typeof ShowsTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/top-rated': {
      id: '/shows/top-rated'
      path: '/shows/top-rated'
      fullPath: '/shows/top-rated'
      preLoaderRoute: typeof ShowsTopRatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/favorites': {
      id: '/shows/favorites'
      path: '/shows/favorites'
      fullPath: '/shows/favorites'
      preLoaderRoute: typeof ShowsFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId': {
      id: '/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof ShowsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/upcoming': {
      id: '/episodes/upcoming'
      path: '/episodes/upcoming'
      fullPath: '/episodes/upcoming'
      preLoaderRoute: typeof EpisodesUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/unwatched': {
      id: '/episodes/unwatched'
      path: '/episodes/unwatched'
      fullPath: '/episodes/unwatched'
      preLoaderRoute: typeof EpisodesUnwatchedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpisodesUnwatchedRoute: EpisodesUnwatchedRoute,
  EpisodesUpcomingRoute: EpisodesUpcomingRoute,
  ShowsShowIdRoute: ShowsShowIdRoute,
  ShowsFavoritesRoute: ShowsFavoritesRoute,
  ShowsTopRatedRoute: ShowsTopRatedRoute,
  ShowsTrendingRoute: ShowsTrendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
